export const industryOverviewIcons = {
  automobile: [
    new URL("../../assets/images/industries/automobile/icon/icon1.png", import.meta.url).href,
    new URL("../../assets/images/industries/automobile/icon/icon2.png", import.meta.url).href,
    new URL("../../assets/images/industries/automobile/icon/icon3.png", import.meta.url).href,
    new URL("../../assets/images/industries/automobile/icon/icon4.png", import.meta.url).href,
    new URL("../../assets/images/industries/automobile/icon/icon5.png", import.meta.url).href,
    new URL("../../assets/images/industries/automobile/icon/icon6.png", import.meta.url).href,
    new URL("../../assets/images/industries/automobile/icon/icon7.png", import.meta.url).href,
    new URL("../../assets/images/industries/automobile/icon/icon7.png", import.meta.url).href,
  ],
  chemical: [
    new URL("../../assets/images/industries/chemical/icon/icon1.png", import.meta.url).href,
    new URL("../../assets/images/industries/chemical/icon/icon2.png", import.meta.url).href,
    new URL("../../assets/images/industries/chemical/icon/icon3.png", import.meta.url).href,
    new URL("../../assets/images/industries/chemical/icon/icon4.png", import.meta.url).href,
    new URL("../../assets/images/industries/chemical/icon/icon5.png", import.meta.url).href,
    new URL("../../assets/images/industries/chemical/icon/icon6.png", import.meta.url).href,
    new URL("../../assets/images/industries/chemical/icon/icon7.png", import.meta.url).href,
    new URL("../../assets/images/industries/chemical/icon/icon7.png", import.meta.url).href,
  ],
  electrical: [
    new URL("../../assets/images/industries/electronic/icon/icon1.png", import.meta.url).href,
    new URL("../../assets/images/industries/electronic/icon/icon2.png", import.meta.url).href,
    new URL("../../assets/images/industries/electronic/icon/icon3.png", import.meta.url).href,
    new URL("../../assets/images/industries/electronic/icon/icon4.png", import.meta.url).href,
    new URL("../../assets/images/industries/electronic/icon/icon5.png", import.meta.url).href,
    new URL("../../assets/images/industries/electronic/icon/icon6.png", import.meta.url).href,
    new URL("../../assets/images/industries/electronic/icon/icon7.png", import.meta.url).href,
    new URL("../../assets/images/industries/electronic/icon/icon7.png", import.meta.url).href,
  ],
  food: [
    new URL("../../assets/images/industries/food/icon/icon1.png", import.meta.url).href,
    new URL("../../assets/images/industries/food/icon/icon2.png", import.meta.url).href,
    new URL("../../assets/images/industries/food/icon/icon3.png", import.meta.url).href,
    new URL("../../assets/images/industries/food/icon/icon4.png", import.meta.url).href,
    new URL("../../assets/images/industries/food/icon/icon5.png", import.meta.url).href,
    new URL("../../assets/images/industries/food/icon/icon6.png", import.meta.url).href,
    new URL("../../assets/images/industries/food/icon/icon7.png", import.meta.url).href,
    new URL("../../assets/images/industries/food/icon/icon7.png", import.meta.url).href,
  ],
  infrastructure: [
    new URL("../../assets/images/industries/Infrastructure/icon/icon1.png", import.meta.url).href,
    new URL("../../assets/images/industries/Infrastructure/icon/icon2.png", import.meta.url).href,
    new URL("../../assets/images/industries/Infrastructure/icon/icon3.png", import.meta.url).href,
    new URL("../../assets/images/industries/Infrastructure/icon/icon4.png", import.meta.url).href,
    new URL("../../assets/images/industries/Infrastructure/icon/icon5.png", import.meta.url).href,
    new URL("../../assets/images/industries/Infrastructure/icon/icon6.png", import.meta.url).href,
    new URL("../../assets/images/industries/Infrastructure/icon/icon7.png", import.meta.url).href,
    new URL("../../assets/images/industries/Infrastructure/icon/icon7.png", import.meta.url).href,
  ],
  irrigation: [
    new URL("../../assets/images/industries/Irrigation/icon/icon1.png", import.meta.url).href,
    new URL("../../assets/images/industries/Irrigation/icon/icon2.png", import.meta.url).href,
    new URL("../../assets/images/industries/Irrigation/icon/icon3.png", import.meta.url).href,
    new URL("../../assets/images/industries/Irrigation/icon/icon4.png", import.meta.url).href,
    new URL("../../assets/images/industries/Irrigation/icon/icon5.png", import.meta.url).href,
    new URL("../../assets/images/industries/Irrigation/icon/icon6.png", import.meta.url).href,
    new URL("../../assets/images/industries/Irrigation/icon/icon7.png", import.meta.url).href,
    new URL("../../assets/images/industries/Irrigation/icon/icon7.png", import.meta.url).href,
  ],
  labware: [
    new URL("../../assets/images/industries/labware/icon/icon1.png", import.meta.url).href,
    new URL("../../assets/images/industries/labware/icon/icon2.png", import.meta.url).href,
    new URL("../../assets/images/industries/labware/icon/icon3.png", import.meta.url).href,
    new URL("../../assets/images/industries/labware/icon/icon4.png", import.meta.url).href,
    new URL("../../assets/images/industries/labware/icon/icon5.png", import.meta.url).href,
    new URL("../../assets/images/industries/labware/icon/icon6.png", import.meta.url).href,
    new URL("../../assets/images/industries/labware/icon/icon7.png", import.meta.url).href,
    new URL("../../assets/images/industries/labware/icon/icon7.png", import.meta.url).href,
  ],
  medical: [
    new URL("../../assets/images/industries/medical/icon/icon1.png", import.meta.url).href,
    new URL("../../assets/images/industries/medical/icon/icon2.png", import.meta.url).href,
    new URL("../../assets/images/industries/medical/icon/icon3.png", import.meta.url).href,
    new URL("../../assets/images/industries/medical/icon/icon4.png", import.meta.url).href,
    new URL("../../assets/images/industries/medical/icon/icon5.png", import.meta.url).href,
    new URL("../../assets/images/industries/medical/icon/icon6.png", import.meta.url).href,
    new URL("../../assets/images/industries/medical/icon/icon7.png", import.meta.url).href,
    new URL("../../assets/images/industries/medical/icon/icon7.png", import.meta.url).href,
  ],
  oil: [
    new URL("../../assets/images/industries/oil/icon/icon1.png", import.meta.url).href,
    new URL("../../assets/images/industries/oil/icon/icon2.png", import.meta.url).href,
    new URL("../../assets/images/industries/oil/icon/icon3.png", import.meta.url).href,
    new URL("../../assets/images/industries/oil/icon/icon4.png", import.meta.url).href,
    new URL("../../assets/images/industries/oil/icon/icon5.png", import.meta.url).href,
    new URL("../../assets/images/industries/oil/icon/icon6.png", import.meta.url).href,
    new URL("../../assets/images/industries/oil/icon/icon7.png", import.meta.url).href,
    new URL("../../assets/images/industries/oil/icon/icon7.png", import.meta.url).href,
  ],
};
